/* tslint:disable */
/* eslint-disable */
/**
 * Tally API
 * Minimal OpenAPI surface for watchlist v2. Expand with real schemas per route as we iterate.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiWatchlistUserShowIdStatusPut200Response
 */
export interface ApiWatchlistUserShowIdStatusPut200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ApiWatchlistUserShowIdStatusPut200Response
     */
    success?: boolean;
}

/**
 * Check if a given object implements the ApiWatchlistUserShowIdStatusPut200Response interface.
 */
export function instanceOfApiWatchlistUserShowIdStatusPut200Response(value: object): value is ApiWatchlistUserShowIdStatusPut200Response {
    return true;
}

export function ApiWatchlistUserShowIdStatusPut200ResponseFromJSON(json: any): ApiWatchlistUserShowIdStatusPut200Response {
    return ApiWatchlistUserShowIdStatusPut200ResponseFromJSONTyped(json, false);
}

export function ApiWatchlistUserShowIdStatusPut200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiWatchlistUserShowIdStatusPut200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function ApiWatchlistUserShowIdStatusPut200ResponseToJSON(json: any): ApiWatchlistUserShowIdStatusPut200Response {
    return ApiWatchlistUserShowIdStatusPut200ResponseToJSONTyped(json, false);
}

export function ApiWatchlistUserShowIdStatusPut200ResponseToJSONTyped(value?: ApiWatchlistUserShowIdStatusPut200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

