/* tslint:disable */
/* eslint-disable */
/**
 * Tally API
 * Minimal OpenAPI surface for watchlist v2. Expand with real schemas per route as we iterate.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserShowCard } from './UserShowCard';
import {
    UserShowCardFromJSON,
    UserShowCardFromJSONTyped,
    UserShowCardToJSON,
    UserShowCardToJSONTyped,
} from './UserShowCard';

/**
 * 
 * @export
 * @interface ApiWatchlistGet200Response
 */
export interface ApiWatchlistGet200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiWatchlistGet200Response
     */
    count?: number;
    /**
     * 
     * @type {Array<UserShowCard>}
     * @memberof ApiWatchlistGet200Response
     */
    shows: Array<UserShowCard>;
}

/**
 * Check if a given object implements the ApiWatchlistGet200Response interface.
 */
export function instanceOfApiWatchlistGet200Response(value: object): value is ApiWatchlistGet200Response {
    if (!('shows' in value) || value['shows'] === undefined) return false;
    return true;
}

export function ApiWatchlistGet200ResponseFromJSON(json: any): ApiWatchlistGet200Response {
    return ApiWatchlistGet200ResponseFromJSONTyped(json, false);
}

export function ApiWatchlistGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiWatchlistGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'shows': ((json['shows'] as Array<any>).map(UserShowCardFromJSON)),
    };
}

export function ApiWatchlistGet200ResponseToJSON(json: any): ApiWatchlistGet200Response {
    return ApiWatchlistGet200ResponseToJSONTyped(json, false);
}

export function ApiWatchlistGet200ResponseToJSONTyped(value?: ApiWatchlistGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'shows': ((value['shows'] as Array<any>).map(UserShowCardToJSON)),
    };
}

