/* tslint:disable */
/* eslint-disable */
/**
 * Tally API
 * Minimal OpenAPI surface for watchlist v2. Expand with real schemas per route as we iterate.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiWatchlistStatsGet200ResponseByStatus } from './ApiWatchlistStatsGet200ResponseByStatus';
import {
    ApiWatchlistStatsGet200ResponseByStatusFromJSON,
    ApiWatchlistStatsGet200ResponseByStatusFromJSONTyped,
    ApiWatchlistStatsGet200ResponseByStatusToJSON,
    ApiWatchlistStatsGet200ResponseByStatusToJSONTyped,
} from './ApiWatchlistStatsGet200ResponseByStatus';

/**
 * 
 * @export
 * @interface ApiWatchlistStatsGet200Response
 */
export interface ApiWatchlistStatsGet200Response {
    /**
     * 
     * @type {number}
     * @memberof ApiWatchlistStatsGet200Response
     */
    totalShows: number;
    /**
     * 
     * @type {ApiWatchlistStatsGet200ResponseByStatus}
     * @memberof ApiWatchlistStatsGet200Response
     */
    byStatus: ApiWatchlistStatsGet200ResponseByStatus;
    /**
     * 
     * @type {number}
     * @memberof ApiWatchlistStatsGet200Response
     */
    averageRating: number;
}

/**
 * Check if a given object implements the ApiWatchlistStatsGet200Response interface.
 */
export function instanceOfApiWatchlistStatsGet200Response(value: object): value is ApiWatchlistStatsGet200Response {
    if (!('totalShows' in value) || value['totalShows'] === undefined) return false;
    if (!('byStatus' in value) || value['byStatus'] === undefined) return false;
    if (!('averageRating' in value) || value['averageRating'] === undefined) return false;
    return true;
}

export function ApiWatchlistStatsGet200ResponseFromJSON(json: any): ApiWatchlistStatsGet200Response {
    return ApiWatchlistStatsGet200ResponseFromJSONTyped(json, false);
}

export function ApiWatchlistStatsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiWatchlistStatsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'totalShows': json['totalShows'],
        'byStatus': ApiWatchlistStatsGet200ResponseByStatusFromJSON(json['byStatus']),
        'averageRating': json['averageRating'],
    };
}

export function ApiWatchlistStatsGet200ResponseToJSON(json: any): ApiWatchlistStatsGet200Response {
    return ApiWatchlistStatsGet200ResponseToJSONTyped(json, false);
}

export function ApiWatchlistStatsGet200ResponseToJSONTyped(value?: ApiWatchlistStatsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalShows': value['totalShows'],
        'byStatus': ApiWatchlistStatsGet200ResponseByStatusToJSON(value['byStatus']),
        'averageRating': value['averageRating'],
    };
}

