/* tslint:disable */
/* eslint-disable */
/**
 * Tally API
 * Minimal OpenAPI surface for watchlist v2. Expand with real schemas per route as we iterate.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ApiWatchlistStatsGet200ResponseByStatus
 */
export interface ApiWatchlistStatsGet200ResponseByStatus {
  /**
   *
   * @type {number}
   * @memberof ApiWatchlistStatsGet200ResponseByStatus
   */
  watchlist: number;
  /**
   *
   * @type {number}
   * @memberof ApiWatchlistStatsGet200ResponseByStatus
   */
  watching: number;
  /**
   *
   * @type {number}
   * @memberof ApiWatchlistStatsGet200ResponseByStatus
   */
  completed: number;
  /**
   *
   * @type {number}
   * @memberof ApiWatchlistStatsGet200ResponseByStatus
   */
  dropped: number;
}

/**
 * Check if a given object implements the ApiWatchlistStatsGet200ResponseByStatus interface.
 */
export function instanceOfApiWatchlistStatsGet200ResponseByStatus(
  value: object
): value is ApiWatchlistStatsGet200ResponseByStatus {
  if (!('watchlist' in value) || value['watchlist'] === undefined) return false;
  if (!('watching' in value) || value['watching'] === undefined) return false;
  if (!('completed' in value) || value['completed'] === undefined) return false;
  if (!('dropped' in value) || value['dropped'] === undefined) return false;
  return true;
}

export function ApiWatchlistStatsGet200ResponseByStatusFromJSON(
  json: any
): ApiWatchlistStatsGet200ResponseByStatus {
  return ApiWatchlistStatsGet200ResponseByStatusFromJSONTyped(json, false);
}

export function ApiWatchlistStatsGet200ResponseByStatusFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiWatchlistStatsGet200ResponseByStatus {
  if (json == null) {
    return json;
  }
  return {
    watchlist: json['watchlist'],
    watching: json['watching'],
    completed: json['completed'],
    dropped: json['dropped'],
  };
}

export function ApiWatchlistStatsGet200ResponseByStatusToJSON(
  json: any
): ApiWatchlistStatsGet200ResponseByStatus {
  return ApiWatchlistStatsGet200ResponseByStatusToJSONTyped(json, false);
}

export function ApiWatchlistStatsGet200ResponseByStatusToJSONTyped(
  value?: ApiWatchlistStatsGet200ResponseByStatus | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    watchlist: value['watchlist'],
    watching: value['watching'],
    completed: value['completed'],
    dropped: value['dropped'],
  };
}
