/* tslint:disable */
/* eslint-disable */
/**
 * Tally API
 * Minimal OpenAPI surface for watchlist v2. Expand with real schemas per route as we iterate.
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ProgressUpdateRequest
 */
export interface ProgressUpdateRequest {
  /**
   *
   * @type {string}
   * @memberof ProgressUpdateRequest
   */
  state?: ProgressUpdateRequestStateEnum;
  /**
   *
   * @type {number}
   * @memberof ProgressUpdateRequest
   */
  progress?: number;
  /**
   *
   * @type {Date}
   * @memberof ProgressUpdateRequest
   */
  startedWatchingAt?: Date;
  /**
   *
   * @type {Date}
   * @memberof ProgressUpdateRequest
   */
  watchedAt?: Date;
}

/**
 * @export
 */
export const ProgressUpdateRequestStateEnum = {
  Watched: 'watched',
  Unwatched: 'unwatched',
} as const;
export type ProgressUpdateRequestStateEnum =
  (typeof ProgressUpdateRequestStateEnum)[keyof typeof ProgressUpdateRequestStateEnum];

/**
 * Check if a given object implements the ProgressUpdateRequest interface.
 */
export function instanceOfProgressUpdateRequest(value: object): value is ProgressUpdateRequest {
  return true;
}

export function ProgressUpdateRequestFromJSON(json: any): ProgressUpdateRequest {
  return ProgressUpdateRequestFromJSONTyped(json, false);
}

export function ProgressUpdateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ProgressUpdateRequest {
  if (json == null) {
    return json;
  }
  return {
    state: json['state'] == null ? undefined : json['state'],
    progress: json['progress'] == null ? undefined : json['progress'],
    startedWatchingAt:
      json['started_watching_at'] == null ? undefined : new Date(json['started_watching_at']),
    watchedAt: json['watched_at'] == null ? undefined : new Date(json['watched_at']),
  };
}

export function ProgressUpdateRequestToJSON(json: any): ProgressUpdateRequest {
  return ProgressUpdateRequestToJSONTyped(json, false);
}

export function ProgressUpdateRequestToJSONTyped(
  value?: ProgressUpdateRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    state: value['state'],
    progress: value['progress'],
    started_watching_at:
      value['startedWatchingAt'] == null ? undefined : value['startedWatchingAt'].toISOString(),
    watched_at: value['watchedAt'] == null ? undefined : value['watchedAt'].toISOString(),
  };
}
