/* tslint:disable */
/* eslint-disable */
/**
 * Tally API
 * Minimal OpenAPI surface for watchlist v2. Expand with real schemas per route as we iterate.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Progress
 */
export interface Progress {
    /**
     * 
     * @type {number}
     * @memberof Progress
     */
    watchedEps?: number;
    /**
     * 
     * @type {number}
     * @memberof Progress
     */
    totalEps?: number;
    /**
     * 
     * @type {number}
     * @memberof Progress
     */
    watchedEpsLatest?: number;
    /**
     * 
     * @type {number}
     * @memberof Progress
     */
    totalEpsLatest?: number;
}

/**
 * Check if a given object implements the Progress interface.
 */
export function instanceOfProgress(value: object): value is Progress {
    return true;
}

export function ProgressFromJSON(json: any): Progress {
    return ProgressFromJSONTyped(json, false);
}

export function ProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): Progress {
    if (json == null) {
        return json;
    }
    return {
        
        'watchedEps': json['watched_eps'] == null ? undefined : json['watched_eps'],
        'totalEps': json['total_eps'] == null ? undefined : json['total_eps'],
        'watchedEpsLatest': json['watched_eps_latest'] == null ? undefined : json['watched_eps_latest'],
        'totalEpsLatest': json['total_eps_latest'] == null ? undefined : json['total_eps_latest'],
    };
}

export function ProgressToJSON(json: any): Progress {
    return ProgressToJSONTyped(json, false);
}

export function ProgressToJSONTyped(value?: Progress | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'watched_eps': value['watchedEps'],
        'total_eps': value['totalEps'],
        'watched_eps_latest': value['watchedEpsLatest'],
        'total_eps_latest': value['totalEpsLatest'],
    };
}

