/* tslint:disable */
/* eslint-disable */
/**
 * Tally API
 * Minimal OpenAPI surface for watchlist v2. Expand with real schemas per route as we iterate.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateStatusRequest
 */
export interface UpdateStatusRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateStatusRequest
     */
    status: UpdateStatusRequestStatusEnum;
}


/**
 * @export
 */
export const UpdateStatusRequestStatusEnum = {
    Watchlist: 'watchlist',
    Watching: 'watching',
    Completed: 'completed'
} as const;
export type UpdateStatusRequestStatusEnum = typeof UpdateStatusRequestStatusEnum[keyof typeof UpdateStatusRequestStatusEnum];


/**
 * Check if a given object implements the UpdateStatusRequest interface.
 */
export function instanceOfUpdateStatusRequest(value: object): value is UpdateStatusRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function UpdateStatusRequestFromJSON(json: any): UpdateStatusRequest {
    return UpdateStatusRequestFromJSONTyped(json, false);
}

export function UpdateStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function UpdateStatusRequestToJSON(json: any): UpdateStatusRequest {
    return UpdateStatusRequestToJSONTyped(json, false);
}

export function UpdateStatusRequestToJSONTyped(value?: UpdateStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

