/* tslint:disable */
/* eslint-disable */
/**
 * Tally API
 * Minimal OpenAPI surface for watchlist v2. Expand with real schemas per route as we iterate.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRatingRequest
 */
export interface UpdateRatingRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateRatingRequest
     */
    rating: number;
}

/**
 * Check if a given object implements the UpdateRatingRequest interface.
 */
export function instanceOfUpdateRatingRequest(value: object): value is UpdateRatingRequest {
    if (!('rating' in value) || value['rating'] === undefined) return false;
    return true;
}

export function UpdateRatingRequestFromJSON(json: any): UpdateRatingRequest {
    return UpdateRatingRequestFromJSONTyped(json, false);
}

export function UpdateRatingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRatingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rating': json['rating'],
    };
}

export function UpdateRatingRequestToJSON(json: any): UpdateRatingRequest {
    return UpdateRatingRequestToJSONTyped(json, false);
}

export function UpdateRatingRequestToJSONTyped(value?: UpdateRatingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rating': value['rating'],
    };
}

